### PR TITLE
fix(Elife): separate address span with commas

### PR DESCRIPTION
**Pull request by nlisgo**

### CODE REVIEW

**Comment by nlisgo** [comment]
@alex-ketch we have introduced the comma to the appropriate elements but there is some whitespace in the template that is affecting the presentation. If this whitespace is needed perhaps you could introduce it with css?

Screenshot 2020-11-20 at 10 00 13
Screenshot 2020-11-20 at 10 01 47


when I remove the whitespace from the dom in the browser:

Screenshot 2020-11-20 at 10 03 06
Screenshot 2020-11-20 at 10 03 21

**Comment by nokome** [comment]
Thanks for this @nlisgo 

It seems that the whitespace is introduced by Encoda's pretty printing indenting the `<address>` element in `thema/src/examples/articleReplication.html`:

```html
    <li itemscope="" itemtype="http://schema.org/Organization" itemid="#author-organization-1"
      id="author-organization-1"><span itemprop="name">University of Georgia, Bioexpression and
        Fermentation Facility</span>
      <address itemscope="" itemtype="http://schema.org/PostalAddress" itemprop="address"><span
          itemprop="addressLocality">Georgia</span><span itemprop="addressCountry">United
          States</span></address>
    </li>
```

Note that there is no trailing whitespace in the `<span itemprop="name">` element and if you remove the indentation of `<address>` the extra whitespace goes away.

Two options for changes in Encoda to rectify this:

- use `<span itemscope="" itemtype="http://schema.org/PostalAddress" itemprop="address">` instead of `<address ....>`
- turn off indenting of `<address>` elems

**Comment by nokome** [comment]
Encoda v0.103.1 fixes this and there is a PR to upgrade it in this repo: https://github.com/stencila/thema/pull/258/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R69

@alex-ketch I suggest that this be merged.

**Review by nokome — APPROVED** [review]

**Comment by alex-ketch** [comment]
Sounds good @nokome, will merge the Encoda/dev-dependencies PR first and then this.

**Comment by nlisgo** [comment]
@alex-ketch when can we expect this to be deployed to production. It should fix the presentation of affiliations on this article: https://elifesciences.org/articles/43154/executable

**Comment by alex-ketch** [comment]
Hi @nlisgo, all the dependencies have been updated for the Stencila Hub and awaiting automatic release. Once that's done, I will re-generate the article snapshot to fix the issue and notify you.

**Comment by nokome** [comment]
Hi @nlisgo . Hope you are well. Just wanted to let you know that I am in the process of updating snapshots (the latest version of Encoda was deployed today) for some of the earlier ERAs. The reason this is taking a little longer than expected is because I am "upgrading" the source R Markdown to use some of newer syntax such as proper table captions and internal links.

**Comment by nlisgo** [comment]
@nokome these changes still seem to have not been rolled out yet.

**Comment by nokome** [comment]
Changes now applied to the Errington article in this snapshot: https://hub.stenci.la/elife/article-30274/snapshots/16

**Pull request merged**
