### PR TITLE
chore(CI): Remove old branch name from config

### PR DESCRIPTION
**Pull request by davidcmoulton**
Noticed this old branch name in there, so removed it.

### CODE REVIEW

**Comment by alex-ketch** [comment]
Not sure about this, might be nice to keep ability to publish release candidate packages in the future. Do you have any thoughts @nokome?

**Comment by nokome** [comment]
IMO, the whole `branches` section can be be removed (and, with the general aim of removing cruft, should). It is a safelist : https://docs.travis-ci.com/user/customizing-the-build#safelisting-or-blocklisting-branches. So either remove it completely or retain `next` (for future use).

**Comment by alex-ketch** [comment]
@nokome Removing the branches section will create double builds, no?
https://github.com/stencila/thema/pull/46

**Comment by nokome** [comment]
I really don't know and don't want to spend hours trying to understand it. Will just close this PR - the extra branch name is not doing any harm - but removing it sound like it might.

**Pull request closed without merging**
