### PR TITLE
feat(Elife): link to the new labs post directly

### PR DESCRIPTION
**Pull request by nlisgo**
Currently we are linking to an old labs post and have a redirect in place. This will allow us to restore the old labs post.

### CODE REVIEW

**Comment by nlisgo** [comment]
This is far less urgent than https://github.com/stencila/thema/pull/238

This is just tidy up.

**Review by discodavey — APPROVED** [review]

**Comment by nlisgo** [comment]
@alex-ketch this still hasn't been deployed yet? I thought you had a CD pipeline, is that not the case?

**Comment by discodavey** [comment]
@nlisgo Do you know what the latest is with this?

**Comment by nlisgo** [comment]
@discodavey I just know that it hasn't been deployed yet despite merging it in 3 weeks ago.

**Comment by discodavey** [comment]
Is this something that needs to be sorted by Stencila or are we in control of this?

**Comment by nlisgo** [comment]
> Is this something that needs to be sorted by Stencila or are we in control of this?

If there is a deploy button somewhere that I have control of, I am not aware of it :)

**Comment by discodavey** [comment]
Thanks @alex-ketch

**Pull request merged**
