### PR TITLE
eLife: ERA pre-launch style refinements

### PR DESCRIPTION
**Pull request by alex-ketch**
@chugginselifesciences  Please note that I've refactored the `CodeChunk` component since we last spoke to move the menu bar and the code editor to the left. This allows for consistency in both the code/output element order and the (toggle source, run) action buttons between the inline `CodeExpression` and the block `CodeChunk` components.
I'm more than happy to pair again tomorrow if you have further pre-launch feedback.

As for the other changes:
- As discussed the `run` button is only shown once the source code is revealed. It now appears _after_ the `show/hide` button
- Buttons now have a solid fill for much higher hierarchy
- We're using using solid icons for buttons for more prominence
- Code element background and border colours are using the eLife colour variables
- The article hero has been adjusted to place the `download` icon 14px below the toolbar. There's a pixel or two misalignment with the `lock` icon to the left which I haven't touched as I wasn't sure if that was done for optical alignment or not.

@discodavey, @NuclearRedeye Please let me know if you have any questions or would like me to further document specific code sections.

---

**Preview**

Screenshot 2020-08-03 at 22 06 25@2x

### CODE REVIEW

**Comment by discodavey** [comment]
@alex-ketch I have pulled down the PR and none of the icons are showing locally. I have run an npm install, bootstrap and an update and none of these work. Any other ideas?

Screen grab below

Screenshot 2020-08-04 at 09 15 57

**Comment by chugginselifesciences** [comment]
Hi @alex-ketch - this looks great. Thanks for all your help. Besides the SVG issue Dave raised above, can I check we got the blue button hover colour right? I might have given you the wrong hex value yesterday. 

If it's not already `#0277BD` would you mind updating it? Thanks.

**Comment by NuclearRedeye** [comment]
Note, the icons not loading seems to be a CORS issue. I've tried enabling CORS in the webpack-dev-server config...
```
    devServer: {
      contentBase: path.join(__dirname, contentBase),
      overlay: true,
      https: true,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': '*',
        'Access-Control-Allow-Methods': '*',
      },
    },
```

But I still can't get it to work.

**Comment by alex-ketch** [comment]
Thanks for looking into this @NuclearRedeye, turns out that in trying to use an SVG symbol set for the icons was problematic due to the SVG `use` element [not supporting cross-origin policies](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use) for fetching resources.
I've [changed the approach](https://github.com/stencila/designa/pull/77) for including icons in, which avoids this issue.

**Pull request merged**
